name: Build Windows runtime (test)
on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tagged version to build
        required: false
      commit:
        type: string
        required: false
        description: SHA of the commit to build (no release will be produced)
  push:
    tags:
      - 'v*-*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out runtime source code
        uses: actions/checkout@v4
      - name: Build CLR for Windows
        run: .\build.cmd -c Release -Pack -Publish /p:VersionSuffix=criteo1 /p:StabilizePackageVersion=false /p:OfficialBuildId=20201010.1 /p:NativeOptimizationDataSupported=false /p:IncludeSymbols=true
      - name: Generate layout
        run: |
          cd src/tests
          .\build.cmd Release -generatelayoutonly
      - name: List tests generated directory
        run: dir -Recurse artifacts\tests\coreclr
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-runtime
          path: artifacts/packages/Release/Shipping/
      - name: Upload Non shipping artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-runtime-nonshipping
          path: artifacts/packages/Release/NonShipping/
      - name: Upload tests artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-runtime-tests
          path: artifacts/tests/coreclr/
