name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream8
    env:
      DOTNET_TOOLS_DIR: /github/home/.dotnet/tools
    steps:
      - name : Download dotnet install scripts
        shell: bash
        run: |
          wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
          chmod u+x ./dotnet-install.sh
      - name: Install .NET SDK and dotnet-symbol
        shell: bash
        run: |
          mkdir -p dotnet-sdk
          ./dotnet-install.sh --os linux --install-dir dotnet-sdk
          chmod u+x dotnet-sdk/dotnet
          dotnet-sdk/dotnet tool install dotnet-symbol -g
      - name: Test
        shell: bash
        run: |
          ${{env.DOTNET_TOOLS_DIR]]/dotnet-symbol
    
    
